apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docappsystem
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mokshitgupta/docapp-gitops.git'
    targetRevision: main
    path: . 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: docapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
