services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: docappdb
      DB_USER: docuser
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 3306
      DJANGO_SETTINGS_MODULE: docappsystem.settings
    command: >
      sh -c "./wait-for-it.sh db:3306 -- 
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: docappdb
      MYSQL_USER: docuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    command: --default-authentication-plugin=mysql_native_password --skip-ssl
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 10
