# Generated by Django 5.1.6 on 2025-05-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0018_onlineconsultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('online', 'Online Video Consultation'), ('offline', 'In-Person Clinic Visit')], default='offline', max_length=20),
        ),
    ]
