# Generated by Django 5.1.6 on 2025-05-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0019_appointment_consultation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='consultation_type',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('offline', 'In-Person Visit'), ('online', 'Online Consultation')], default='offline', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'doc')], default=1, max_length=50),
        ),
    ]
